<?php

namespace gestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * chambreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class chambreRepository extends EntityRepository
{
}
