<?php

namespace gestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * sejoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sejoursRepository extends EntityRepository
{
}
