<?php

namespace gestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * serviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class serviceRepository extends EntityRepository
{
}
